name: flutter_previewer
description: "Flutter Previewer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  device_frame: ^1.4.0
  device_preview: ^1.3.1
  lite_state: ^4.1.0
  figma_squircle: ^0.6.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.1.0
  provider: ^6.1.2
  url_launcher: ^6.0.7
  flutter_staggered_grid_view: ^0.7.0
  ecommerce_001:
    path: ./projects/ecommerce_001

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
